deep experience in planning, designing and implementing banking application systems. 
ability to conceptualize banking in terms of processes, data, systems and architecture.



* cover
dear sir/madam

This is regarding the position of

The near collapse of Knight Trading highlites the criticallity of IT and operations

On my professional IT Banking career, I have had the opportunity to be involved in the architecture, design and implemtation of
various systems and processi. Affecting several teams. 


My roles have allowed me to work on all IT Operation segements. from implementing systems to detect risk in the back-office, to the mid-ofice analytical tool
validation to fron-office proviing tools and system for trading desk to evaluate and anticipate risk and pnl expaln

Beyond teaching, my experience liansing with interactive banking groups ( quant analtyics, IT, complience) has given me
opportunity to present, promote and sell and engage. All these skills would come handy on the SMU role requiring

On the personal side, I enjoy mentoring, and bring complext subjects to wais that not are only 
but 
I am confident that my educational background, professional experience and personal drive continues will allow me to add value to the
.....program and to the students

AR: cc enoch and steven
